### ISSUE TITLE
Usage with Webpack

### ISSUE THREAD

**Issue by ArnoBuschmann** [MattMcFarland/react-markdown-area#1]
Hi Matt,

I like how react-markdown-area uses Github flavored markdown nicely.

I just seem to have issues using it in conjunction with Webpack.

Basically Webpack is complaining about lack of loaders for the file types .less and .js:

```
ERROR in ./~/react-markdown-area/less/markedarea.less
Module parse failed: path to.../node_modules/react-markdown-area/less/markedarea.less Line 1: Unexpected token .
You may need an appropriate loader to handle this file type.
| .marked-area {
|   border: thin solid #bababa;
|   display: block;
 @ ./~/react-markdown-area/index.js 1:0-33

ERROR in ./~/react-markdown-area/lib/markedarea.js
Module parse failed: path to.../node_modules/react-markdown-area/lib/markedarea.js Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import React from 'react';
| import marked from 'marked';
| export default class MarkedArea extends React.Component {
 @ ./~/react-markdown-area/index.js 2:21-48
```

I am using postcss but adding a less-loader like this works so far:

```
test: /\.less$/,
loader: "style!css!less"
```

Just then for .js-files I have defined that node-modules are excluded, which makes sense and should stay:

```
test: /\.js?$/,
exclude: /node_modules/,
loader: 'babel?optional=es7.decorators'
```

What would you suggest in this case?

**Comment by MattMcFarland** [comment]
Hi Arno,

Were you able to get it working?  Or do you think we should have some modifications to the source to add support for webpack?  I haven't used this with webpack yet, as I've been primarily using browserify.

I assumed it would work with webpack as well, but if there are errors that can be addressed in the source I'd love to get them in.

**Comment by ArnoBuschmann** [comment]
No, unfortunately I didn't got it working. I tried to use the dist file directly: `import {MarkedArea} from '../../node_modules/react-markdown-area/dist/markedarea';` but that is throwing other errors.

I noticed, the built dist file markedarea.js is with 1.6 mb quite huge, does it need to be so big?

I am no Webpack specialist and wouldn't know, how to get it addressed specifically. But I can say I am using a lot other packages that have been npm installed and Webpack isn't complaining about them at all.

No need to change the package especially for me. Just as Webpack is widely used, I thought it would be nice if react-markdown-area works with it as well, so I opened this issue.

**Comment by MattMcFarland** [comment]
Ah thanks Arno!

Yes I agree with you that webpack should work with it.  The 1.6mb file is huge indeed!!

I'll fix these issues in the next version, thanks for pointing this out.

**Comment by MattMcFarland** [comment]
Hi,

I've just released v0.1.0 - can you try it out?  I think it should work with webpack jsut fine.  Only thing you'll have to manually copy over the css file from the lib or dist folder.

Thanks!

**Comment by ArnoBuschmann** [comment]
Hi Matt,

just installed it, but getting an error message

`Uncaught TypeError: Cannot read property 'Component' of undefined  markedarea.js?c00a:193`

Line 193 in your markedarea.js: `})(_react2.default.Component);`

**Comment by MattMcFarland** [comment]
Arno, can you share some source code?

**Comment by ArnoBuschmann** [comment]
Matt, not exactly sure what source code you mean. But this is how I installed the module:

`import MarkedArea from 'react-markdown-area';` then called it with `<MarkedArea label="My label" placeholder="My placeholder"/>`

The error mentioned above is referring to the script `/node_modules/react-markdown-area/lib/markedarea.js` line 193 where it calls .Component, which seems to be undefined.

Another warning I get from Webpack during server startup (the moment where it produces the bundle) is:

```WARNING in ./~/react-markdown-area/lib/markedarea.js
Critical dependencies:
21:483-490 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/react-markdown-area/lib/markedarea.js 21:483-490

```

Hope this helps, let me know if I can check on anything else.
```

**Comment by MattMcFarland** [comment]
Can you try pulling in the src/ file?  I was hoping to avoid that as to not
complicate things with babel, etc.

On Thu, Dec 3, 2015 at 4:17 PM, ArnoBuschmann notifications@github.com
wrote:

> Matt, not exactly sure what source code you mean. But this is how I
> installed the module:
> 
> import MarkedArea from 'react-markdown-area'; then called it with <MarkedArea
> label="My label" placeholder="My placeholder"/>
> 
> The error mentioned above is referring to the script
> /node_modules/react-markdown-area/lib/markedarea.js line 193 where it
> calls .Component, which seems to be undefined.
> 
> Another warning I get from Webpack during server startup (the moment where
> it produces the bundle) is:
> 
> ```WARNING in ./~/react-markdown-area/lib/markedarea.js
> Critical dependencies:
> 21:483-490 This seems to be a pre-built javascript file. Though this is
> possible, it's not recommended. Try to require the original source to get
> better results.
> @ ./~/react-markdown-area/lib/markedarea.js 21:483-490
> 
> Hope this helps, let me know if I can check on anything else.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MattMcFarland/react-markdown-area/issues/1#issuecomment-161787358
> .

## 

Matt McFarland

Software Engineer | @docodemore https://twitter.com/docodemore | LinkedIn
http://www.linkedin.com/pub/matthew-mcfarland/6a/b9a/135/en | Mobile:
513.638.8685 | Office: 937.865.6800 xt: 125010

**Comment by ArnoBuschmann** [comment]
Just did by importing: `import MarkedArea from '../../node_modules/react-markdown-area/dist/markedarea';` Same error messages.

**Comment by MattMcFarland** [comment]
try `require('../../node_modules/react-markdown-area/dist/markedarea').default` - for some weird reason maybe its the later version of babel

**Comment by ArnoBuschmann** [comment]
Tried, still the same.

**Comment by MattMcFarland** [comment]
Ok..  This will work for webpack if its the last thing I do!!!!!  Thanks
for your patience, I'll have a fix before the end of the week.

On Thu, Dec 3, 2015 at 4:37 PM, ArnoBuschmann notifications@github.com
wrote:

> Tried, still the same.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MattMcFarland/react-markdown-area/issues/1#issuecomment-161792026
> .

## 

Matt McFarland

Software Engineer | @docodemore https://twitter.com/docodemore | LinkedIn
http://www.linkedin.com/pub/matthew-mcfarland/6a/b9a/135/en | Mobile:
513.638.8685 | Office: 937.865.6800 xt: 125010

**Comment by ArnoBuschmann** [comment]
No problem, glad if I can help :)

**Comment by MattMcFarland** [comment]
I think I got it fixed.. sorry for the lateness!!

**Comment by MattMcFarland** [comment]
No response, closing
